#!/bin/sh

# Mono, why u no support Client profile?
xbuild /verbosity:minimal /tv:4.0 /p:TargetFrameworkProfile="" /p:Framework="NET40" IronSmarkets/IronSmarkets.csproj && \
xbuild /verbosity:minimal /tv:4.0 /p:TargetFrameworkProfile="" /p:Framework="NET40" IronSmarkets.ConsoleExample/IronSmarkets.ConsoleExample.csproj && \
xbuild /verbosity:minimal /tv:4.0 /p:TargetFrameworkProfile="" /p:Framework="NET40" IronSmarkets.Tests/IronSmarkets.Tests.csproj

xbuild /verbosity:minimal /tv:3.5 /p:Framework="NET35" IronSmarkets/IronSmarkets.csproj && \
xbuild /verbosity:minimal /tv:3.5 /p:Framework="NET35" IronSmarkets.ConsoleExample/IronSmarkets.ConsoleExample.csproj && \
xbuild /verbosity:minimal /tv:3.5 /p:Framework="NET35" IronSmarkets.Tests/IronSmarkets.Tests.csproj
