#!/bin/sh

# Mono, why u no support Client profile?
xbuild /p:TargetFrameworkProfile="" IronSmarkets/IronSmarkets.csproj
xbuild /p:TargetFrameworkProfile="" IronSmarkets.ConsoleExample/IronSmarkets.ConsoleExample.csproj
xbuild /p:TargetFrameworkProfile="" IronSmarkets.Tests/IronSmarkets.Tests.csproj
