//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: smarkets.eto.piqi.proto
namespace IronSmarkets.Proto.Eto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Payload")]
  public partial class Payload : global::ProtoBuf.IExtensible
  {
    public Payload() {}
    
    private ulong _seq;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Seq
    {
      get { return _seq; }
      set { _seq = value; }
    }

    private IronSmarkets.Proto.Eto.PayloadType _type = IronSmarkets.Proto.Eto.PayloadType.PAYLOADNONE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(IronSmarkets.Proto.Eto.PayloadType.PAYLOADNONE)]
    public IronSmarkets.Proto.Eto.PayloadType Type
    {
      get { return _type; }
      set { _type = value; }
    }

    private bool _isReplay = (bool)false;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"is_replay", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool IsReplay
    {
      get { return _isReplay; }
      set { _isReplay = value; }
    }

    private IronSmarkets.Proto.Eto.Replay _replay = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"replay", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Eto.Replay Replay
    {
      get { return _replay; }
      set { _replay = value; }
    }

    private IronSmarkets.Proto.Eto.Login _login = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"login", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Eto.Login Login
    {
      get { return _login; }
      set { _login = value; }
    }

    private IronSmarkets.Proto.Eto.LoginResponse _loginResponse = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"login_response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Eto.LoginResponse LoginResponse
    {
      get { return _loginResponse; }
      set { _loginResponse = value; }
    }

    private IronSmarkets.Proto.Eto.Logout _logout = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"logout", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Eto.Logout Logout
    {
      get { return _logout; }
      set { _logout = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Replay")]
  public partial class Replay : global::ProtoBuf.IExtensible
  {
    public Replay() {}
    
    private ulong _seq;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Seq
    {
      get { return _seq; }
      set { _seq = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Login")]
  public partial class Login : global::ProtoBuf.IExtensible
  {
    public Login() {}
    
    private string _session;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Session
    {
      get { return _session; }
      set { _session = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResponse")]
  public partial class LoginResponse : global::ProtoBuf.IExtensible
  {
    public LoginResponse() {}
    
    private string _session;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Session
    {
      get { return _session; }
      set { _session = value; }
    }

    private ulong _reset = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Reset
    {
      get { return _reset; }
      set { _reset = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Logout")]
  public partial class Logout : global::ProtoBuf.IExtensible
  {
    public Logout() {}
    

    private IronSmarkets.Proto.Eto.LogoutReason _reason = IronSmarkets.Proto.Eto.LogoutReason.LOGOUTNONE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(IronSmarkets.Proto.Eto.LogoutReason.LOGOUTNONE)]
    public IronSmarkets.Proto.Eto.LogoutReason Reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"PayloadType")]
    public enum PayloadType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_NONE", Value=1)]
      PAYLOADNONE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_PING", Value=2)]
      PAYLOADPING = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_PONG", Value=3)]
      PAYLOADPONG = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_GAPFILL", Value=4)]
      PAYLOADGAPFILL = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_HEARTBEAT", Value=5)]
      PAYLOADHEARTBEAT = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_REPLAY", Value=6)]
      PAYLOADREPLAY = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_LOGIN", Value=7)]
      PAYLOADLOGIN = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_LOGIN_RESPONSE", Value=8)]
      PAYLOADLOGINRESPONSE = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_LOGOUT", Value=9)]
      PAYLOADLOGOUT = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LogoutReason")]
    public enum LogoutReason
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGOUT_NONE", Value=1)]
      LOGOUTNONE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGOUT_HEARTBEAT_TIMEOUT", Value=2)]
      LOGOUTHEARTBEATTIMEOUT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGOUT_CONFIRMATION", Value=3)]
      LOGOUTCONFIRMATION = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGOUT_LOGIN_TIMEOUT", Value=4)]
      LOGOUTLOGINTIMEOUT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGOUT_LOGIN_NOT_FIRST_SEQ", Value=5)]
      LOGOUTLOGINNOTFIRSTSEQ = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGOUT_UNKNOWN_SESSION", Value=6)]
      LOGOUTUNKNOWNSESSION = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGOUT_UNAUTHORISED", Value=7)]
      LOGOUTUNAUTHORISED = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGOUT_SERVICE_TEMPORARILY_UNAVAILABLE", Value=8)]
      LOGOUTSERVICETEMPORARILYUNAVAILABLE = 8
    }
  
}
