//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: smarkets.seto.piqi.proto
// Note: requires additional types generated from: smarkets.eto.piqi.proto
namespace IronSmarkets.Proto.Seto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"event")]
  public partial class Event : global::ProtoBuf.IExtensible
  {
    public Event() {}
    
    private ulong _low;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"low", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Low
    {
      get { return _low; }
      set { _low = value; }
    }

    private ulong _high = (ulong)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"high", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)0)]
    public ulong High
    {
      get { return _high; }
      set { _high = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"market")]
  public partial class Market : global::ProtoBuf.IExtensible
  {
    public Market() {}
    
    private ulong _low;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"low", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Low
    {
      get { return _low; }
      set { _low = value; }
    }

    private ulong _high = (ulong)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"high", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)0)]
    public ulong High
    {
      get { return _high; }
      set { _high = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"contract")]
  public partial class Contract : global::ProtoBuf.IExtensible
  {
    public Contract() {}
    
    private ulong _low;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"low", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Low
    {
      get { return _low; }
      set { _low = value; }
    }

    private ulong _high = (ulong)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"high", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)0)]
    public ulong High
    {
      get { return _high; }
      set { _high = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"order")]
  public partial class Order : global::ProtoBuf.IExtensible
  {
    public Order() {}
    
    private ulong _low;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"low", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Low
    {
      get { return _low; }
      set { _low = value; }
    }

    private ulong _high = (ulong)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"high", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)0)]
    public ulong High
    {
      get { return _high; }
      set { _high = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"entity")]
  public partial class Entity : global::ProtoBuf.IExtensible
  {
    public Entity() {}
    
    private ulong _low;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"low", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Low
    {
      get { return _low; }
      set { _low = value; }
    }

    private ulong _high = (ulong)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"high", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)0)]
    public ulong High
    {
      get { return _high; }
      set { _high = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Payload")]
  public partial class Payload : global::ProtoBuf.IExtensible
  {
    public Payload() {}
    
    private IronSmarkets.Proto.Seto.PayloadType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.PayloadType Type
    {
      get { return _type; }
      set { _type = value; }
    }
    private IronSmarkets.Proto.Eto.Payload _etoPayload;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"eto_payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Eto.Payload EtoPayload
    {
      get { return _etoPayload; }
      set { _etoPayload = value; }
    }

    private IronSmarkets.Proto.Seto.Login _login = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"login", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.Login Login
    {
      get { return _login; }
      set { _login = value; }
    }

    private IronSmarkets.Proto.Seto.OrderCreate _orderCreate = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"order_create", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.OrderCreate OrderCreate
    {
      get { return _orderCreate; }
      set { _orderCreate = value; }
    }

    private IronSmarkets.Proto.Seto.OrderRejected _orderRejected = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"order_rejected", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.OrderRejected OrderRejected
    {
      get { return _orderRejected; }
      set { _orderRejected = value; }
    }

    private IronSmarkets.Proto.Seto.OrderAccepted _orderAccepted = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"order_accepted", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.OrderAccepted OrderAccepted
    {
      get { return _orderAccepted; }
      set { _orderAccepted = value; }
    }

    private IronSmarkets.Proto.Seto.OrderExecuted _orderExecuted = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"order_executed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.OrderExecuted OrderExecuted
    {
      get { return _orderExecuted; }
      set { _orderExecuted = value; }
    }

    private IronSmarkets.Proto.Seto.OrderCancel _orderCancel = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"order_cancel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.OrderCancel OrderCancel
    {
      get { return _orderCancel; }
      set { _orderCancel = value; }
    }

    private IronSmarkets.Proto.Seto.OrderCancelled _orderCancelled = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"order_cancelled", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.OrderCancelled OrderCancelled
    {
      get { return _orderCancelled; }
      set { _orderCancelled = value; }
    }

    private IronSmarkets.Proto.Seto.OrderInvalid _orderInvalid = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"order_invalid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.OrderInvalid OrderInvalid
    {
      get { return _orderInvalid; }
      set { _orderInvalid = value; }
    }

    private IronSmarkets.Proto.Seto.MarketSubscribe _marketSubscribe = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"market_subscribe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.MarketSubscribe MarketSubscribe
    {
      get { return _marketSubscribe; }
      set { _marketSubscribe = value; }
    }

    private IronSmarkets.Proto.Seto.MarketUnsubscribe _marketUnsubscribe = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"market_unsubscribe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.MarketUnsubscribe MarketUnsubscribe
    {
      get { return _marketUnsubscribe; }
      set { _marketUnsubscribe = value; }
    }

    private IronSmarkets.Proto.Seto.MarketQuotesRequest _marketQuotesRequest = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"market_quotes_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.MarketQuotesRequest MarketQuotesRequest
    {
      get { return _marketQuotesRequest; }
      set { _marketQuotesRequest = value; }
    }

    private IronSmarkets.Proto.Seto.MarketQuotes _marketQuotes = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"market_quotes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.MarketQuotes MarketQuotes
    {
      get { return _marketQuotes; }
      set { _marketQuotes = value; }
    }

    private IronSmarkets.Proto.Seto.ContractQuotes _contractQuotes = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"contract_quotes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.ContractQuotes ContractQuotes
    {
      get { return _contractQuotes; }
      set { _contractQuotes = value; }
    }

    private IronSmarkets.Proto.Seto.EventsRequest _eventsRequest = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"events_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.EventsRequest EventsRequest
    {
      get { return _eventsRequest; }
      set { _eventsRequest = value; }
    }

    private IronSmarkets.Proto.Seto.HttpFound _httpFound = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"http_found", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.HttpFound HttpFound
    {
      get { return _httpFound; }
      set { _httpFound = value; }
    }

    private IronSmarkets.Proto.Seto.InvalidRequest _invalidRequest = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"invalid_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.InvalidRequest InvalidRequest
    {
      get { return _invalidRequest; }
      set { _invalidRequest = value; }
    }

    private IronSmarkets.Proto.Seto.OrderCancelRejected _orderCancelRejected = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"order_cancel_rejected", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.OrderCancelRejected OrderCancelRejected
    {
      get { return _orderCancelRejected; }
      set { _orderCancelRejected = value; }
    }

    private IronSmarkets.Proto.Seto.OrdersForAccountRequest _ordersForAccountRequest = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"orders_for_account_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.OrdersForAccountRequest OrdersForAccountRequest
    {
      get { return _ordersForAccountRequest; }
      set { _ordersForAccountRequest = value; }
    }

    private IronSmarkets.Proto.Seto.OrdersForAccount _ordersForAccount = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"orders_for_account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.OrdersForAccount OrdersForAccount
    {
      get { return _ordersForAccount; }
      set { _ordersForAccount = value; }
    }

    private IronSmarkets.Proto.Seto.OrdersForMarketRequest _ordersForMarketRequest = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"orders_for_market_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.OrdersForMarketRequest OrdersForMarketRequest
    {
      get { return _ordersForMarketRequest; }
      set { _ordersForMarketRequest = value; }
    }

    private IronSmarkets.Proto.Seto.OrdersForMarket _ordersForMarket = null;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"orders_for_market", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.OrdersForMarket OrdersForMarket
    {
      get { return _ordersForMarket; }
      set { _ordersForMarket = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Uuid128")]
  public partial class Uuid128 : global::ProtoBuf.IExtensible
  {
    public Uuid128() {}
    
    private ulong _low;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"low", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Low
    {
      get { return _low; }
      set { _low = value; }
    }

    private ulong _high = (ulong)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"high", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)0)]
    public ulong High
    {
      get { return _high; }
      set { _high = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Login")]
  public partial class Login : global::ProtoBuf.IExtensible
  {
    public Login() {}
    

    private string _username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Username
    {
      get { return _username; }
      set { _username = value; }
    }

    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _password; }
      set { _password = value; }
    }

    private byte[] _cookie = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cookie", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] Cookie
    {
      get { return _cookie; }
      set { _cookie = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderCreate")]
  public partial class OrderCreate : global::ProtoBuf.IExtensible
  {
    public OrderCreate() {}
    
    private IronSmarkets.Proto.Seto.OrderCreateType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.OrderCreateType Type
    {
      get { return _type; }
      set { _type = value; }
    }
    private IronSmarkets.Proto.Seto.Uuid128 _market;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"market", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Market
    {
      get { return _market; }
      set { _market = value; }
    }
    private IronSmarkets.Proto.Seto.Uuid128 _contract;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"contract", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Contract
    {
      get { return _contract; }
      set { _contract = value; }
    }
    private IronSmarkets.Proto.Seto.Side _side;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"side", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.Side Side
    {
      get { return _side; }
      set { _side = value; }
    }
    private IronSmarkets.Proto.Seto.QuantityType _quantityType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"quantity_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.QuantityType QuantityType
    {
      get { return _quantityType; }
      set { _quantityType = value; }
    }
    private uint _quantity;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"quantity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Quantity
    {
      get { return _quantity; }
      set { _quantity = value; }
    }

    private IronSmarkets.Proto.Seto.PriceType _priceType = IronSmarkets.Proto.Seto.PriceType.PRICEPERCENTODDS;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"price_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(IronSmarkets.Proto.Seto.PriceType.PRICEPERCENTODDS)]
    public IronSmarkets.Proto.Seto.PriceType PriceType
    {
      get { return _priceType; }
      set { _priceType = value; }
    }

    private uint _price = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Price
    {
      get { return _price; }
      set { _price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderRejected")]
  public partial class OrderRejected : global::ProtoBuf.IExtensible
  {
    public OrderRejected() {}
    
    private ulong _seq;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Seq
    {
      get { return _seq; }
      set { _seq = value; }
    }
    private IronSmarkets.Proto.Seto.OrderRejectedReason _reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.OrderRejectedReason Reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderCancelRejected")]
  public partial class OrderCancelRejected : global::ProtoBuf.IExtensible
  {
    public OrderCancelRejected() {}
    
    private ulong _seq;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Seq
    {
      get { return _seq; }
      set { _seq = value; }
    }
    private IronSmarkets.Proto.Seto.OrderCancelRejectedReason _reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.OrderCancelRejectedReason Reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderAccepted")]
  public partial class OrderAccepted : global::ProtoBuf.IExtensible
  {
    public OrderAccepted() {}
    
    private ulong _seq;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Seq
    {
      get { return _seq; }
      set { _seq = value; }
    }
    private IronSmarkets.Proto.Seto.Uuid128 _order;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Order
    {
      get { return _order; }
      set { _order = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderExecuted")]
  public partial class OrderExecuted : global::ProtoBuf.IExtensible
  {
    public OrderExecuted() {}
    
    private IronSmarkets.Proto.Seto.Uuid128 _order;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Order
    {
      get { return _order; }
      set { _order = value; }
    }
    private uint _price;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Price
    {
      get { return _price; }
      set { _price = value; }
    }
    private IronSmarkets.Proto.Seto.QuantityType _quantityType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"quantity_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.QuantityType QuantityType
    {
      get { return _quantityType; }
      set { _quantityType = value; }
    }
    private uint _quantity;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"quantity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Quantity
    {
      get { return _quantity; }
      set { _quantity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderCancel")]
  public partial class OrderCancel : global::ProtoBuf.IExtensible
  {
    public OrderCancel() {}
    
    private IronSmarkets.Proto.Seto.Uuid128 _order;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Order
    {
      get { return _order; }
      set { _order = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderCancelled")]
  public partial class OrderCancelled : global::ProtoBuf.IExtensible
  {
    public OrderCancelled() {}
    
    private IronSmarkets.Proto.Seto.Uuid128 _order;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Order
    {
      get { return _order; }
      set { _order = value; }
    }
    private IronSmarkets.Proto.Seto.OrderCancelledReason _reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.OrderCancelledReason Reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderInvalid")]
  public partial class OrderInvalid : global::ProtoBuf.IExtensible
  {
    public OrderInvalid() {}
    
    private ulong _seq;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Seq
    {
      get { return _seq; }
      set { _seq = value; }
    }
    private readonly global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.OrderInvalidReason> _reasons = new global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.OrderInvalidReason>();
    [global::ProtoBuf.ProtoMember(2, Name=@"reasons", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.OrderInvalidReason> Reasons
    {
      get { return _reasons; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MarketSubscribe")]
  public partial class MarketSubscribe : global::ProtoBuf.IExtensible
  {
    public MarketSubscribe() {}
    
    private IronSmarkets.Proto.Seto.Uuid128 _market;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"market", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Market
    {
      get { return _market; }
      set { _market = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MarketUnsubscribe")]
  public partial class MarketUnsubscribe : global::ProtoBuf.IExtensible
  {
    public MarketUnsubscribe() {}
    
    private IronSmarkets.Proto.Seto.Uuid128 _market;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"market", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Market
    {
      get { return _market; }
      set { _market = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MarketQuotesRequest")]
  public partial class MarketQuotesRequest : global::ProtoBuf.IExtensible
  {
    public MarketQuotesRequest() {}
    
    private IronSmarkets.Proto.Seto.Uuid128 _market;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"market", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Market
    {
      get { return _market; }
      set { _market = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MarketQuotes")]
  public partial class MarketQuotes : global::ProtoBuf.IExtensible
  {
    public MarketQuotes() {}
    
    private IronSmarkets.Proto.Seto.Uuid128 _market;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"market", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Market
    {
      get { return _market; }
      set { _market = value; }
    }
    private readonly global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.ContractQuotes> _contractQuotes = new global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.ContractQuotes>();
    [global::ProtoBuf.ProtoMember(2, Name=@"contract_quotes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.ContractQuotes> ContractQuotes
    {
      get { return _contractQuotes; }
    }
  
    private IronSmarkets.Proto.Seto.PriceType _priceType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"price_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.PriceType PriceType
    {
      get { return _priceType; }
      set { _priceType = value; }
    }
    private IronSmarkets.Proto.Seto.QuantityType _quantityType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"quantity_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.QuantityType QuantityType
    {
      get { return _quantityType; }
      set { _quantityType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ContractQuotes")]
  public partial class ContractQuotes : global::ProtoBuf.IExtensible
  {
    public ContractQuotes() {}
    
    private IronSmarkets.Proto.Seto.Uuid128 _contract;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"contract", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Contract
    {
      get { return _contract; }
      set { _contract = value; }
    }
    private readonly global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.Quote> _bids = new global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.Quote>();
    [global::ProtoBuf.ProtoMember(2, Name=@"bids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.Quote> Bids
    {
      get { return _bids; }
    }
  
    private readonly global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.Quote> _offers = new global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.Quote>();
    [global::ProtoBuf.ProtoMember(3, Name=@"offers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.Quote> Offers
    {
      get { return _offers; }
    }
  
    private readonly global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.Execution> _executions = new global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.Execution>();
    [global::ProtoBuf.ProtoMember(4, Name=@"executions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.Execution> Executions
    {
      get { return _executions; }
    }
  

    private IronSmarkets.Proto.Seto.Execution _lastExecution = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"last_execution", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.Execution LastExecution
    {
      get { return _lastExecution; }
      set { _lastExecution = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Quote")]
  public partial class Quote : global::ProtoBuf.IExtensible
  {
    public Quote() {}
    
    private uint _price;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Price
    {
      get { return _price; }
      set { _price = value; }
    }
    private uint _quantity;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"quantity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Quantity
    {
      get { return _quantity; }
      set { _quantity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Execution")]
  public partial class Execution : global::ProtoBuf.IExtensible
  {
    public Execution() {}
    
    private uint _price;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Price
    {
      get { return _price; }
      set { _price = value; }
    }
    private uint _quantity;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"quantity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Quantity
    {
      get { return _quantity; }
      set { _quantity = value; }
    }
    private IronSmarkets.Proto.Seto.Side _liquidity;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"liquidity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.Side Liquidity
    {
      get { return _liquidity; }
      set { _liquidity = value; }
    }
    private ulong _microseconds;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"microseconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Microseconds
    {
      get { return _microseconds; }
      set { _microseconds = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EventsRequest")]
  public partial class EventsRequest : global::ProtoBuf.IExtensible
  {
    public EventsRequest() {}
    
    private IronSmarkets.Proto.Seto.EventsRequestType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.EventsRequestType Type
    {
      get { return _type; }
      set { _type = value; }
    }
    private IronSmarkets.Proto.Seto.ContentType _contentType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"content_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.ContentType ContentType
    {
      get { return _contentType; }
      set { _contentType = value; }
    }

    private IronSmarkets.Proto.Seto.SportByDate _sportByDate = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sport_by_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.SportByDate SportByDate
    {
      get { return _sportByDate; }
      set { _sportByDate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SportByDate")]
  public partial class SportByDate : global::ProtoBuf.IExtensible
  {
    public SportByDate() {}
    
    private IronSmarkets.Proto.Seto.SportByDateType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.SportByDateType Type
    {
      get { return _type; }
      set { _type = value; }
    }
    private IronSmarkets.Proto.Seto.Date _date;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Date Date
    {
      get { return _date; }
      set { _date = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Events")]
  public partial class Events : global::ProtoBuf.IExtensible
  {
    public Events() {}
    
    private readonly global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.EventInfo> _withMarkets = new global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.EventInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"with_markets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.EventInfo> WithMarkets
    {
      get { return _withMarkets; }
    }
  
    private readonly global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.EventInfo> _parents = new global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.EventInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"parents", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.EventInfo> Parents
    {
      get { return _parents; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EventInfo")]
  public partial class EventInfo : global::ProtoBuf.IExtensible
  {
    public EventInfo() {}
    
    private IronSmarkets.Proto.Seto.Uuid128 _event;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"event", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Event
    {
      get { return _event; }
      set { _event = value; }
    }
    private IronSmarkets.Proto.Seto.EventType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.EventType Type
    {
      get { return _type; }
      set { _type = value; }
    }
    private IronSmarkets.Proto.Seto.EventCategory _category;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.EventCategory Category
    {
      get { return _category; }
      set { _category = value; }
    }
    private string _slug;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"slug", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Slug
    {
      get { return _slug; }
      set { _slug = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _name; }
      set { _name = value; }
    }

    private IronSmarkets.Proto.Seto.Uuid128 _parent = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"parent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.Uuid128 Parent
    {
      get { return _parent; }
      set { _parent = value; }
    }

    private IronSmarkets.Proto.Seto.Date _startDate = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"start_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.Date StartDate
    {
      get { return _startDate; }
      set { _startDate = value; }
    }

    private IronSmarkets.Proto.Seto.Time _startTime = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"start_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.Time StartTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }

    private IronSmarkets.Proto.Seto.Date _endDate = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"end_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.Date EndDate
    {
      get { return _endDate; }
      set { _endDate = value; }
    }

    private IronSmarkets.Proto.Seto.Time _endTime = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"end_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.Time EndTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private readonly global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.EntityRelationship> _entities = new global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.EntityRelationship>();
    [global::ProtoBuf.ProtoMember(11, Name=@"entities", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.EntityRelationship> Entities
    {
      get { return _entities; }
    }
  
    private readonly global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.MarketInfo> _markets = new global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.MarketInfo>();
    [global::ProtoBuf.ProtoMember(12, Name=@"markets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.MarketInfo> Markets
    {
      get { return _markets; }
    }
  

    private string _description = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Description
    {
      get { return _description; }
      set { _description = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MarketInfo")]
  public partial class MarketInfo : global::ProtoBuf.IExtensible
  {
    public MarketInfo() {}
    
    private IronSmarkets.Proto.Seto.Uuid128 _market;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"market", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Market
    {
      get { return _market; }
      set { _market = value; }
    }
    private readonly global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.ContractInfo> _contracts = new global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.ContractInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"contracts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.ContractInfo> Contracts
    {
      get { return _contracts; }
    }
  
    private string _slug;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"slug", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Slug
    {
      get { return _slug; }
      set { _slug = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _name; }
      set { _name = value; }
    }

    private IronSmarkets.Proto.Seto.Date _startDate = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"start_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.Date StartDate
    {
      get { return _startDate; }
      set { _startDate = value; }
    }

    private IronSmarkets.Proto.Seto.Time _startTime = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"start_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.Time StartTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }

    private IronSmarkets.Proto.Seto.Date _endDate = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"end_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.Date EndDate
    {
      get { return _endDate; }
      set { _endDate = value; }
    }

    private IronSmarkets.Proto.Seto.Time _endTime = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"end_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IronSmarkets.Proto.Seto.Time EndTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private readonly global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.EntityRelationship> _entities = new global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.EntityRelationship>();
    [global::ProtoBuf.ProtoMember(9, Name=@"entities", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.EntityRelationship> Entities
    {
      get { return _entities; }
    }
  

    private string _shortname = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"shortname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Shortname
    {
      get { return _shortname; }
      set { _shortname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ContractInfo")]
  public partial class ContractInfo : global::ProtoBuf.IExtensible
  {
    public ContractInfo() {}
    
    private IronSmarkets.Proto.Seto.Uuid128 _contract;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"contract", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Contract
    {
      get { return _contract; }
      set { _contract = value; }
    }
    private IronSmarkets.Proto.Seto.ContractType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.ContractType Type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _slug;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"slug", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Slug
    {
      get { return _slug; }
      set { _slug = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.EntityRelationship> _entities = new global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.EntityRelationship>();
    [global::ProtoBuf.ProtoMember(5, Name=@"entities", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.EntityRelationship> Entities
    {
      get { return _entities; }
    }
  

    private string _shortname = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"shortname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Shortname
    {
      get { return _shortname; }
      set { _shortname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EntityRelationship")]
  public partial class EntityRelationship : global::ProtoBuf.IExtensible
  {
    public EntityRelationship() {}
    
    private IronSmarkets.Proto.Seto.Uuid128 _entity;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"entity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Entity
    {
      get { return _entity; }
      set { _entity = value; }
    }
    private IronSmarkets.Proto.Seto.EntityRelationshipType _relationship;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"relationship", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.EntityRelationshipType Relationship
    {
      get { return _relationship; }
      set { _relationship = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HttpFound")]
  public partial class HttpFound : global::ProtoBuf.IExtensible
  {
    public HttpFound() {}
    
    private ulong _seq;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Seq
    {
      get { return _seq; }
      set { _seq = value; }
    }
    private string _url;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Url
    {
      get { return _url; }
      set { _url = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InvalidRequest")]
  public partial class InvalidRequest : global::ProtoBuf.IExtensible
  {
    public InvalidRequest() {}
    
    private ulong _seq;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Seq
    {
      get { return _seq; }
      set { _seq = value; }
    }
    private IronSmarkets.Proto.Seto.InvalidRequestType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.InvalidRequestType Type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Date")]
  public partial class Date : global::ProtoBuf.IExtensible
  {
    public Date() {}
    
    private uint _year;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"year", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Year
    {
      get { return _year; }
      set { _year = value; }
    }
    private uint _month;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"month", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Month
    {
      get { return _month; }
      set { _month = value; }
    }
    private uint _day;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Day
    {
      get { return _day; }
      set { _day = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Time")]
  public partial class Time : global::ProtoBuf.IExtensible
  {
    public Time() {}
    
    private uint _hour;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Hour
    {
      get { return _hour; }
      set { _hour = value; }
    }
    private uint _minute;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"minute", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Minute
    {
      get { return _minute; }
      set { _minute = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"orders_for_account_request")]
  public partial class OrdersForAccountRequest : global::ProtoBuf.IExtensible
  {
    public OrdersForAccountRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"orders_for_account")]
  public partial class OrdersForAccount : global::ProtoBuf.IExtensible
  {
    public OrdersForAccount() {}
    
    private readonly global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.OrdersForMarket> _markets = new global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.OrdersForMarket>();
    [global::ProtoBuf.ProtoMember(1, Name=@"markets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.OrdersForMarket> Markets
    {
      get { return _markets; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"orders_for_market_request")]
  public partial class OrdersForMarketRequest : global::ProtoBuf.IExtensible
  {
    public OrdersForMarketRequest() {}
    
    private IronSmarkets.Proto.Seto.Uuid128 _market;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"market", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Market
    {
      get { return _market; }
      set { _market = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"orders_for_market")]
  public partial class OrdersForMarket : global::ProtoBuf.IExtensible
  {
    public OrdersForMarket() {}
    
    private IronSmarkets.Proto.Seto.Uuid128 _market;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"market", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Market
    {
      get { return _market; }
      set { _market = value; }
    }
    private IronSmarkets.Proto.Seto.PriceType _priceType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"price_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.PriceType PriceType
    {
      get { return _priceType; }
      set { _priceType = value; }
    }
    private readonly global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.OrdersForContract> _contracts = new global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.OrdersForContract>();
    [global::ProtoBuf.ProtoMember(3, Name=@"contracts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.OrdersForContract> Contracts
    {
      get { return _contracts; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"orders_for_contract")]
  public partial class OrdersForContract : global::ProtoBuf.IExtensible
  {
    public OrdersForContract() {}
    
    private IronSmarkets.Proto.Seto.Uuid128 _contract;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"contract", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Contract
    {
      get { return _contract; }
      set { _contract = value; }
    }
    private readonly global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.OrdersForPrice> _bids = new global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.OrdersForPrice>();
    [global::ProtoBuf.ProtoMember(2, Name=@"bids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.OrdersForPrice> Bids
    {
      get { return _bids; }
    }
  
    private readonly global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.OrdersForPrice> _offers = new global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.OrdersForPrice>();
    [global::ProtoBuf.ProtoMember(3, Name=@"offers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.OrdersForPrice> Offers
    {
      get { return _offers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"orders_for_price")]
  public partial class OrdersForPrice : global::ProtoBuf.IExtensible
  {
    public OrdersForPrice() {}
    
    private uint _price;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Price
    {
      get { return _price; }
      set { _price = value; }
    }
    private readonly global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.OrderState> _orders = new global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.OrderState>();
    [global::ProtoBuf.ProtoMember(2, Name=@"orders", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<IronSmarkets.Proto.Seto.OrderState> Orders
    {
      get { return _orders; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderState")]
  public partial class OrderState : global::ProtoBuf.IExtensible
  {
    public OrderState() {}
    
    private IronSmarkets.Proto.Seto.Uuid128 _order;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public IronSmarkets.Proto.Seto.Uuid128 Order
    {
      get { return _order; }
      set { _order = value; }
    }
    private IronSmarkets.Proto.Seto.OrderCreateType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.OrderCreateType Type
    {
      get { return _type; }
      set { _type = value; }
    }
    private IronSmarkets.Proto.Seto.OrderStatus _status;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.OrderStatus Status
    {
      get { return _status; }
      set { _status = value; }
    }
    private IronSmarkets.Proto.Seto.QuantityType _quantityType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"quantity_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public IronSmarkets.Proto.Seto.QuantityType QuantityType
    {
      get { return _quantityType; }
      set { _quantityType = value; }
    }
    private uint _quantity;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"quantity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Quantity
    {
      get { return _quantity; }
      set { _quantity = value; }
    }
    private ulong _createdMicroseconds;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"created_microseconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong CreatedMicroseconds
    {
      get { return _createdMicroseconds; }
      set { _createdMicroseconds = value; }
    }

    private uint _quantityFilled = (uint)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"quantity_filled", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint QuantityFilled
    {
      get { return _quantityFilled; }
      set { _quantityFilled = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"PayloadType")]
    public enum PayloadType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_ETO", Value=1)]
      PAYLOADETO = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_LOGIN", Value=2)]
      PAYLOADLOGIN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_ORDER_CREATE", Value=3)]
      PAYLOADORDERCREATE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_ORDER_REJECTED", Value=4)]
      PAYLOADORDERREJECTED = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_ORDER_ACCEPTED", Value=5)]
      PAYLOADORDERACCEPTED = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_ORDER_EXECUTED", Value=6)]
      PAYLOADORDEREXECUTED = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_ORDER_CANCEL", Value=7)]
      PAYLOADORDERCANCEL = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_ORDER_CANCELLED", Value=8)]
      PAYLOADORDERCANCELLED = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_ORDER_INVALID", Value=9)]
      PAYLOADORDERINVALID = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_MARKET_SUBSCRIBE", Value=10)]
      PAYLOADMARKETSUBSCRIBE = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_MARKET_UNSUBSCRIBE", Value=11)]
      PAYLOADMARKETUNSUBSCRIBE = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_MARKET_QUOTES_REQUEST", Value=12)]
      PAYLOADMARKETQUOTESREQUEST = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_MARKET_QUOTES", Value=13)]
      PAYLOADMARKETQUOTES = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_CONTRACT_QUOTES", Value=14)]
      PAYLOADCONTRACTQUOTES = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_EVENTS_REQUEST", Value=15)]
      PAYLOADEVENTSREQUEST = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_HTTP_FOUND", Value=16)]
      PAYLOADHTTPFOUND = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_INVALID_REQUEST", Value=17)]
      PAYLOADINVALIDREQUEST = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_ORDER_CANCEL_REJECTED", Value=18)]
      PAYLOADORDERCANCELREJECTED = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_ORDERS_FOR_ACCOUNT_REQUEST", Value=19)]
      PAYLOADORDERSFORACCOUNTREQUEST = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_ORDERS_FOR_ACCOUNT", Value=20)]
      PAYLOADORDERSFORACCOUNT = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_ORDERS_FOR_MARKET_REQUEST", Value=21)]
      PAYLOADORDERSFORMARKETREQUEST = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYLOAD_ORDERS_FOR_MARKET", Value=22)]
      PAYLOADORDERSFORMARKET = 22
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"OrderCreateType")]
    public enum OrderCreateType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_CREATE_LIMIT", Value=1)]
      ORDERCREATELIMIT = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"OrderRejectedReason")]
    public enum OrderRejectedReason
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_REJECTED_INSUFFICIENT_FUNDS", Value=1)]
      ORDERREJECTEDINSUFFICIENTFUNDS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_REJECTED_LIMIT_EXCEEDED", Value=2)]
      ORDERREJECTEDLIMITEXCEEDED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_REJECTED_MARKET_NOT_OPEN", Value=3)]
      ORDERREJECTEDMARKETNOTOPEN = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_REJECTED_MARKET_SETTLED", Value=4)]
      ORDERREJECTEDMARKETSETTLED = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_REJECTED_MARKET_HALTED", Value=5)]
      ORDERREJECTEDMARKETHALTED = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_REJECTED_CROSSED_SELF", Value=6)]
      ORDERREJECTEDCROSSEDSELF = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_REJECTED_MARKET_NOT_FOUND", Value=7)]
      ORDERREJECTEDMARKETNOTFOUND = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"OrderCancelRejectedReason")]
    public enum OrderCancelRejectedReason
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_CANCEL_REJECTED_NOT_FOUND", Value=1)]
      ORDERCANCELREJECTEDNOTFOUND = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_CANCEL_REJECTED_NOT_LIVE", Value=2)]
      ORDERCANCELREJECTEDNOTLIVE = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"OrderCancelledReason")]
    public enum OrderCancelledReason
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_CANCELLED_MEMBER_REQUESTED", Value=1)]
      ORDERCANCELLEDMEMBERREQUESTED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_CANCELLED_MARKET_HALTED", Value=2)]
      ORDERCANCELLEDMARKETHALTED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_CANCELLED_INSUFFICIENT_LIQUIDITY", Value=3)]
      ORDERCANCELLEDINSUFFICIENTLIQUIDITY = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"OrderInvalidReason")]
    public enum OrderInvalidReason
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_INVALID_INVALID_PRICE", Value=1)]
      ORDERINVALIDINVALIDPRICE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_INVALID_INVALID_QUANTITY", Value=2)]
      ORDERINVALIDINVALIDQUANTITY = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"QuantityType")]
    public enum QuantityType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUANTITY_PAYOFF_CURRENCY", Value=1)]
      QUANTITYPAYOFFCURRENCY = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PriceType")]
    public enum PriceType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRICE_PERCENT_ODDS", Value=1)]
      PRICEPERCENTODDS = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Side")]
    public enum Side
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SIDE_BUY", Value=1)]
      SIDEBUY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SIDE_SELL", Value=2)]
      SIDESELL = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ContentType")]
    public enum ContentType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONTENT_TYPE_PROTOBUF", Value=1)]
      CONTENTTYPEPROTOBUF = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EventsRequestType")]
    public enum EventsRequestType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENTS_REQUEST_POLITICS", Value=1)]
      EVENTSREQUESTPOLITICS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENTS_REQUEST_CURRENT_AFFAIRS", Value=2)]
      EVENTSREQUESTCURRENTAFFAIRS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENTS_REQUEST_TV_AND_ENTERTAINMENT", Value=3)]
      EVENTSREQUESTTVANDENTERTAINMENT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENTS_REQUEST_SPORT_BY_DATE", Value=4)]
      EVENTSREQUESTSPORTBYDATE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENTS_REQUEST_SPORT_OTHER", Value=5)]
      EVENTSREQUESTSPORTOTHER = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SportByDateType")]
    public enum SportByDateType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SPORT_BY_DATE_FOOTBALL", Value=1)]
      SPORTBYDATEFOOTBALL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SPORT_BY_DATE_HORSE_RACING", Value=2)]
      SPORTBYDATEHORSERACING = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SPORT_BY_DATE_TENNIS", Value=3)]
      SPORTBYDATETENNIS = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ContractType")]
    public enum ContractType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONTRACT_HALF_TIME_FULL_TIME", Value=1)]
      CONTRACTHALFTIMEFULLTIME = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONTRACT_CORRECT_SCORE", Value=2)]
      CONTRACTCORRECTSCORE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONTRACT_GENERIC", Value=3)]
      CONTRACTGENERIC = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONTRACT_WINNER", Value=4)]
      CONTRACTWINNER = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONTRACT_BINARY", Value=5)]
      CONTRACTBINARY = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONTRACT_OVER_UNDER", Value=6)]
      CONTRACTOVERUNDER = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EventType")]
    public enum EventType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_FOOTBALL_MATCH", Value=1)]
      EVENTFOOTBALLMATCH = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_FOOTBALL_SEASON", Value=2)]
      EVENTFOOTBALLSEASON = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_FOOTBALL", Value=3)]
      EVENTFOOTBALL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_GENERIC", Value=4)]
      EVENTGENERIC = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_FOOTBALL_GENERIC", Value=5)]
      EVENTFOOTBALLGENERIC = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_GOLF_SEASON", Value=6)]
      EVENTGOLFSEASON = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_BOXING_SEASON", Value=7)]
      EVENTBOXINGSEASON = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_FORMULA_1_RACE", Value=8)]
      EVENTFORMULA1RACE = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_FORMULA_1_SEASON", Value=9)]
      EVENTFORMULA1SEASON = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_HORSE_RACING_RACE", Value=10)]
      EVENTHORSERACINGRACE = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_HORSE_RACING_COURSE", Value=11)]
      EVENTHORSERACINGCOURSE = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_HORSE_RACING", Value=12)]
      EVENTHORSERACING = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_GOLF_GENERIC", Value=13)]
      EVENTGOLFGENERIC = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_EUROVISION_SEASON", Value=14)]
      EVENTEUROVISIONSEASON = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_TENNIS_MATCH", Value=15)]
      EVENTTENNISMATCH = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_TENNIS_SEASON", Value=16)]
      EVENTTENNISSEASON = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_CYCLING_SEASON", Value=17)]
      EVENTCYCLINGSEASON = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_CYCLING_RACE", Value=18)]
      EVENTCYCLINGRACE = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_MOTOGP_SEASON", Value=19)]
      EVENTMOTOGPSEASON = 19
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EntityRelationshipType")]
    public enum EntityRelationshipType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTITY_RELATIONSHIP_FOOTBALL_HOME_TEAM", Value=1)]
      ENTITYRELATIONSHIPFOOTBALLHOMETEAM = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTITY_RELATIONSHIP_FOOTBALL_AWAY_TEAM", Value=2)]
      ENTITYRELATIONSHIPFOOTBALLAWAYTEAM = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTITY_RELATIONSHIP_FOOTBALL_COMPETITION", Value=3)]
      ENTITYRELATIONSHIPFOOTBALLCOMPETITION = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTITY_RELATIONSHIP_HORSE_RACING_COURSE", Value=4)]
      ENTITYRELATIONSHIPHORSERACINGCOURSE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTITY_RELATIONSHIP_HORSE_RACING_HORSE", Value=5)]
      ENTITYRELATIONSHIPHORSERACINGHORSE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTITY_RELATIONSHIP_HORSE_RACING_JOCKEY", Value=6)]
      ENTITYRELATIONSHIPHORSERACINGJOCKEY = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTITY_RELATIONSHIP_CONTRACT_ASSOCIATED", Value=7)]
      ENTITYRELATIONSHIPCONTRACTASSOCIATED = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTITY_RELATIONSHIP_GENERIC", Value=8)]
      ENTITYRELATIONSHIPGENERIC = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTITY_RELATIONSHIP_TENNIS_PLAYER_A", Value=9)]
      ENTITYRELATIONSHIPTENNISPLAYERA = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTITY_RELATIONSHIP_TENNIS_PLAYER_B", Value=10)]
      ENTITYRELATIONSHIPTENNISPLAYERB = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTITY_RELATIONSHIP_HOME_TEAM", Value=11)]
      ENTITYRELATIONSHIPHOMETEAM = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTITY_RELATIONSHIP_AWAY_TEAM", Value=12)]
      ENTITYRELATIONSHIPAWAYTEAM = 12
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"InvalidRequestType")]
    public enum InvalidRequestType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_REQUEST_DATE_OUT_OF_RANGE", Value=1)]
      INVALIDREQUESTDATEOUTOFRANGE = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EventCategory")]
    public enum EventCategory
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_CATEGORY_SPORT", Value=1)]
      EVENTCATEGORYSPORT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_CATEGORY_POLITICS", Value=2)]
      EVENTCATEGORYPOLITICS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_CATEGORY_CURRENT_AFFAIRS", Value=3)]
      EVENTCATEGORYCURRENTAFFAIRS = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_CATEGORY_TV_AND_ENTERTAINMENT", Value=4)]
      EVENTCATEGORYTVANDENTERTAINMENT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT_CATEGORY_GENERIC", Value=5)]
      EVENTCATEGORYGENERIC = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"order_status")]
    public enum OrderStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_STATUS_LIVE", Value=1)]
      ORDERSTATUSLIVE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_STATUS_PARTIALLY_FILLED", Value=2)]
      ORDERSTATUSPARTIALLYFILLED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_STATUS_FILLED", Value=3)]
      ORDERSTATUSFILLED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_STATUS_PARTIALLY_CANCELLED", Value=4)]
      ORDERSTATUSPARTIALLYCANCELLED = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDER_STATUS_CANCELLED", Value=5)]
      ORDERSTATUSCANCELLED = 5
    }
  
}
